"""empty message

Revision ID: 3ce622a2f0ca
Revises: 8b9538281116
Create Date: 2024-09-26 11:16:57.573097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ce622a2f0ca'
down_revision = '8b9538281116'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('skin_color', sa.String(length=250), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_column('skin_color')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
