"""empty message

Revision ID: 7658bb1b266c
Revises: 3ce622a2f0ca
Create Date: 2024-09-26 12:32:55.011984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7658bb1b266c'
down_revision = '3ce622a2f0ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orbital_period', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('rotation_period', sa.String(length=250), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_column('rotation_period')
        batch_op.drop_column('orbital_period')

    # ### end Alembic commands ###
